<?php if ($block->canSync()): ?>

    <script type="text/javascript">
        require(["jquery"], function ($) {

            var startintegrationurl = '<?= $block->getUrl('adminstedgerintegration/integration/start') ?>';
            var statusintegrationurl = '<?= $block->getUrl('adminstedgerintegration/integration/getprocess') ?>';

            startStedgerIntegration = function () {

                var process = setInterval(
                    function () {
                        $.ajax({
                            url: statusintegrationurl,
                            type: 'GET',
                            complete: function (response) {
                                var html = JSON.parse(response.responseText).content;
                                document.getElementById('content-processing').innerHTML = html;
                            },
                            error: function (xhr, status, errorThrown) {
                                console.log('Error happens. Try again.');
                            }
                        });
                    }, 1000);

                $.ajax({
                    url: startintegrationurl,
                    type: 'GET',
                    complete: function (response) {

                        setTimeout(function () {
                            clearInterval(process);
                        }, 300)

                        var result = JSON.parse(response.responseText);

                        if (result.status == 'error') {
                            alert(result.message);
                        }
                    },
                    error: function (xhr, status, errorThrown) {
                        console.log('Error happens. Try again.');
                    }
                });
            }
        });
    </script>

    <button class="start-integration scalable" type="button" onclick="startStedgerIntegration()">
        Start Integration
    </button>
    <div id="content-processing"></div>

<?php else: ?>
    <div>Please enter a public and a private keys.</div>
<?php endif; ?>